### PR TITLE
add pnpm and yarn to installation guide

### PR DESCRIPTION
**Pull request by fpetrakov**
It would be convenient to have commands for pnpm and yarn as well, as they're quite popular too, what do you think?

### CODE REVIEW

**Comment by molefrog** [comment]
Thank you! Just a minor suggestion: one code block might look slightly better than 3 consecutive ones. How about:

```bash
npm i spoiled

# or using your favourite package manager 
pnpm add spoiled
yarn add spoiled
```

**Comment by fpetrakov** [comment]
@molefrog  Yeah, It would look better, but harder to copy since there would be only one copy button 
image

**Comment by molefrog** [comment]
> @molefrog Yeah, It would look better, but harder to copy since there would be only one copy button image

That's good point. In that case, maybe we can add something like "Or use your package manager of choice:" in between the first block and these two? Sorry I'm being too picky about this, just want it to look better visually 😅

**Comment by fpetrakov** [comment]
@molefrog done, but deployment is failing for some reason, can't check it due to access restrictions

**Comment by molefrog** [comment]
> @molefrog done, but deployment is failing for some reason, can't check it due to access restrictions 

It's not related, should be good after the merge.

**Pull request merged**
