### PR TITLE
Add typeof check for matchMedia

### PR DESCRIPTION
**Pull request by darnfish**

### CODE REVIEW

**Review by molefrog — APPROVED** [review]
Hi @darnfish, thank you for your PR. Just curious, why did the current code not work for you? I assumed that `matchMedia` is a function if it is available, what are the edge cases?

**Comment by darnfish** [comment]
We were running into issues specifically in our tests where matchMedia would be defined on the object but have no value, resulting in:

```
TypeError: matchMedia is not a function
```

**Comment by molefrog** [comment]
Thanks!

**Comment by molefrog** [comment]
Released the latest version.

**Pull request merged**
